# chapter 1

In [1]:
import torch

## Tensors

In [6]:
# init
x = torch.arange(12)

In [7]:
x.shape

torch.Size([12])

In [5]:
X = x.reshape(3, 4)

In [9]:
# all zeros
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# all ones
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
# random (mean = 0, std = 1, gussian distribution)
torch.randn(3, 4)

tensor([[ 0.1877, -0.0436,  1.9949,  1.0534],
        [ 0.6988, -0.0659, -0.7544,  0.9218],
        [-0.3976,  0.6685,  0.8192, -1.8688]])

In [14]:
# with inital val
torch.tensor([[1,2], [3, 4]])

tensor([[1, 2],
        [3, 4]])

## Calculation

In [16]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [21]:
# elementwise
x + y

tensor([ 3.,  4.,  6., 10.])

In [18]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [19]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [20]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [22]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [28]:
# concatenate
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [29]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [30]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [31]:
X.sum()

tensor(66.)

## Boardcast

In [32]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

In [33]:
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [34]:
# boardcast -> duplicates columns in a, duplicates rows in b

In [35]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## Index and slices

In [36]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [38]:
X[1, 2] = 100
X

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 100.,   7.],
        [  8.,   9.,  10.,  11.]])

In [40]:
X[0:2, :] = -1
X

tensor([[-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [ 8.,  9., 10., 11.]])

## Memory Optimization
Some operation would lead to re-allocation of memory, e.g.

In [44]:
before = id(Y)
Y = Y + X
id(Y), before

(4902894656, 4688427136)

In [46]:
# for in-place operation, we need to init an all zero memory block
Z = torch.zeros_like(Y)
before = id(Z)
Z[:] = X + Y
id(Z), before

(4902945792, 4902945792)

In [47]:
# Or we can assign to X[:] or use X+=Y if X is not used in the following steps
before = id(X)
X += Y
id(X) == before

True

## To Numpy

In [48]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [50]:
# to build-in classes
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## Exercise

In [51]:
# Question 1
X < Y

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False, False, False, False]])

In [52]:
X > Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True]])

In [53]:
# Question 2 - board cast 3D tensor
a = torch.zeros((1, 2, 3))
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [55]:
b = torch.zeros((3, 2, 1))
b

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]])

In [56]:
a + b

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [57]:
(a + b).shape

torch.Size([3, 2, 3])